name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  avatars: ^3.0.2
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  getwidget: ^4.0.0
  http: ^1.2.2
  google_nav_bar: ^5.0.7
  image_card: ^0.0.4
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
